### ISSUE TITLE
The population of people, people living in cities, and people not living in cities in each continent.

### ISSUE THREAD

**Issue by Leesh2903** [lewiswatson55/SEM-Group19#26]

**Comment by lewiswatson55** [comment]
SELECT SUM(populationInCities_Country) as populationInCities, SUM(populationNotCities_Country) as populationNotCities, Name
		FROM (
			SELECT country.Population - SUM(city.population) as populationNotCities_Country, city.CountryCode, SUM(city.Population) as populationInCities_Country, country.continent as Name
			FROM city
			JOIN country ON city.CountryCode=country.Code
			GROUP BY city.CountryCode
		) as country_table
		GROUP BY Name
