### ISSUE TITLE
The population of people, people living in cities, and people not living in cities in each country.

### ISSUE THREAD

**Issue by Leesh2903** [lewiswatson55/SEM-Group19#28]

**Comment by lewiswatson55** [comment]
SELECT populationInCities, populationNotCities
FROM (
	SELECT country.Population - SUM(city.population) as populationNotCities, city.CountryCode, SUM(city.Population) as populationInCities
	FROM city
	JOIN country ON city.CountryCode=country.Code
	GROUP BY city.CountryCode
) as tmp_table

**Comment by lewiswatson55** [comment]
SELECT populationInCities, populationNotCities, Name
	FROM (
		SELECT country.Population - SUM(city.population) as populationNotCities, city.CountryCode, SUM(city.Population) as populationInCities, country.Name as Name
		FROM city
		JOIN country ON city.CountryCode=country.Code
		GROUP BY city.CountryCode
	) as country_table
